esphome:
  name: kjokken
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: WIFI
  password: PASSWORD

api:

logger:

ota:

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Kjøkken"
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "Kjøkken"
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
